spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.101:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.zfliu.gulimallproduct.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 1000